### ISSUE TITLE
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed)

### ISSUE THREAD

**Issue by MartinThoma** [SixQuant/nowatermark#15]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/math/.pyenv/versions/3.8.4/lib/python3.8/site-packages/nowatermark/WatermarkRemover.py", line 32, in load_watermark_template
    self.generate_template_gray_and_mask(watermark_template_filename)
  File "/home/math/.pyenv/versions/3.8.4/lib/python3.8/site-packages/nowatermark/WatermarkRemover.py", line 57, in generate_template_gray_and_mask
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.3.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

**Comment by MartinThoma** [comment]
My system:

* WSL2 (Ubuntu 20.04)
* cv2 version 4.3.0
* Python 3.8.4

**Comment by touzilk** [comment]
路径问题，转义一下
