### ISSUE TITLE
执行的时候报错了！

### ISSUE THREAD

**Issue by diegobona** [SixQuant/nowatermark#4]
**>>> remover.load_watermark_template(watermark_template_filename)**
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /tmp/opencv-20180228-11467-1nnr12r/opencv-3.4.1/modules/imgproc/src/color.cpp, line 11147
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/nowatermark/WatermarkRemover.py", line 32, in load_watermark_template
    self.generate_template_gray_and_mask(watermark_template_filename)
  File "/usr/local/lib/python2.7/site-packages/nowatermark/WatermarkRemover.py", line 57, in generate_template_gray_and_mask
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.1) /tmp/opencv-20180228-11467-1nnr12r/opencv-3.4.1/modules/imgproc/src/color.cpp:11147: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by SixQuant** [comment]
你的图片可能搞错了，要彩色的图片
